### PR TITLE
Crypto module fix for angular web applications

### PR DESCRIPTION
**Pull request by aali0730**
fix: Angular web applications are unable to use the crypto library. Replacing it with the crypto-js library allows this plugin to be used in Angular applications.

Signed-off-by: Adrian Ali <aali@forbes.com>

### CODE REVIEW

**Comment by Shelex** [comment]
Hi @aali0730 !
Thank you for opening a pull request. 
Could you please point me to specific issues for angular with node crypto package? As there should be some motivation to introduce another dependency.

**Comment by aali0730** [comment]
@Shelex Hi! I use this plugin on several web applications and it works fine on all except the angular application. Whenever cypress tries on run tests against the angular app, I get this error on my console and no tests run:
`crypto.createHash is not a function`

I looked up this issue and found others reported the same problem with using the crypto library in angular applications. See here:
https://stackoverflow.com/questions/51999812/node-module-aes256-crypto-createhash-is-not-a-function
https://github.com/uport-project/uport-connect/issues/121
https://stackoverflow.com/questions/43353718/how-to-use-crypto-module-in-angular2

I'm current using a local version of this plugin with my crypto-js change applied and it is able to run on the angular app with no errors. I wanted to see if I could merge this change so I can continue using the plugin from this repo instead of using a local modified version of it.

**Comment by Shelex** [comment]
@aali0730 Thank you for your contribution!

**Comment by aali0730** [comment]
Thanks @Shelex ! 😄

**Pull request merged**
